### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by euskadi31** [joyent/http-parser#201]
Hi,

Thank you for your great job, is it possible to release a new version?

**Comment by yosuke-furukawa** [comment]
+1 We need more faster parser for io.js / node .

**Comment by indutny** [comment]
Hm... May be, cc @bnoordhuis

**Comment by indutny** [comment]
Released 2.4.0

**Comment by yosuke-furukawa** [comment]
:100:

**Comment by euskadi31** [comment]
Thx ;)
