### ISSUE TITLE
No http response complete callback

### ISSUE THREAD

**Issue by chenyoufu** [joyent/http-parser#211]
HEAD /PHP/ViewUserInfo.php?userId=10216 HTTP/1.1
User-Agent: curl/7.19.7 (x86_64-unknown-linux-gnu) libcurl/7.19.7 NSS/3.12.7.0 zlib/1.2.5 libidn/1.18 libssh2/1.2.2
Host: 192.168.10.92
Accept: */*

HTTP/1.1 200 OK
Date: Tue, 13 Jan 2015 17:32:49 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.3.3
Connection: close
Content-Type: text/html; charset=UTF-8

The resonse has not Content-length and no body. I find this case I can't arrive on_message_complete at response.
``` c
          } else {
            if (parser->type == HTTP_REQUEST ||
                !http_message_needs_eof(parser)) {
              /* Assume content-length 0 - read the next */
              UPDATE_STATE(NEW_MESSAGE());
              CALLBACK_NOTIFY(message_complete);
            } else {
              /* Read body until EOF */
              UPDATE_STATE(s_body_identity_eof);
            }
          }
        }
```
when the parser UPDATE_STATE(s_body_identity_eof);
then next for loop is false. p = data + len.
``` c
 for (p=data; p != data + len; p++)
```
then goto 
``` c
  assert(((header_field_mark ? 1 : 0) +
          (header_value_mark ? 1 : 0) +
          (url_mark ? 1 : 0)  +
          (body_mark ? 1 : 0) +
          (status_mark ? 1 : 0)) <= 1);

  CALLBACK_DATA_NOADVANCE(header_field);
  CALLBACK_DATA_NOADVANCE(header_value);
  CALLBACK_DATA_NOADVANCE(url);
  CALLBACK_DATA_NOADVANCE(body);
  CALLBACK_DATA_NOADVANCE(status);

  RETURN(len);
```
No road to on_message_complete.

Thanks!

**Comment by indutny** [comment]
Have you tried calling http_parser_execute with 0-byte string on EOF?

**Comment by chenyoufu** [comment]
Thanks. I must  call http_parser_execute with 0-byte string on EOF, then it will go to on_message_complete.

**Comment by indutny** [comment]
Cool! Can we close the issue?

**Comment by tensafe** [comment]
this ?

http_parser_execute(&parser_request, &request_settings_, NULL, 0);

why not call message_complete....

**Comment by arashifunsho** [comment]
Is there any example that can help parse http response string gotten from socket connection on ARM embedded devices.

I need the Response code and Message Body (which is a JSON string that I can parse)

**Comment by 0wnrepo** [comment]
> Thanks. I must call http_parser_execute with 0-byte string on EOF, then it will go to on_message_complete.

I don't understand the logic, why do we need to call that, and how to determine when to call it?

**Comment by ploxiln** [comment]
If there is no explicit Content-Length, then the response goes until the end of the connection.  The connection is closed after sending the full response.

When you read from a tcp connection `read()` returns 0 at end-of-file.

http_parser does not know that it has gotten the last bytes from the connection before it was closed, until you pass that 0, just like you got from read, to http_parser, so it knows.
