### ISSUE TITLE
parser->nread incorrect after removing reexecute goto

### ISSUE THREAD

**Issue by jpinner** [joyent/http-parser#220]
Commit 959f4cb replaced the "reexecute_byte" goto with a pointer decrement and break statement. The result is that whenever a byte is re-executed, the count header size macro is also re-executed, resulting in an incorrect value for parser->nread.

**Comment by indutny** [comment]
Confirmed. Looking.

**Comment by indutny** [comment]
Should be fixed by https://github.com/joyent/http-parser/pull/221

**Comment by indutny** [comment]
Fixed in 7ecf775, thank you!

**Comment by jpinner** [comment]
one nit: unnecessary trailing '\' in the #define
