### ISSUE TITLE
Add support for gzip encoding

### ISSUE THREAD

**Issue by bibhas2** [joyent/http-parser#226]
Gzip is a widely used content encoding. It will be really helpful if the parser could detect gzip encoding from the header and then uncompress the received data and pass to on_body callback.

**Comment by indutny** [comment]
It is actually really easy to implement in a user-space, not sure if there is any point in doing this in the parser library itself, considering how low-level it is.

**Comment by marcomorain** [comment]
Agreed - a HTTP header parser should not decode the HTTP body. The header
parser should do 1 thing and do it well.

**Comment by indutny** [comment]
Sorry, but won't fix.
