### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by choupani** [joyent/http-parser#227]
Hi,
Do you have any plan to support http version 2?

**Comment by indutny** [comment]
Hello!

Not in this repo, but yeah.

**Comment by johnzachary** [comment]
Which repo will support HTTP/2?

**Comment by mkozjak** [comment]
@johnzachary +1

**Comment by pkoretic** [comment]
@indutny can you please share more info on it? Thanks!

**Comment by xiaokai-wang** [comment]
please share more, thanks!
