### ISSUE TITLE
Violating Access Everytime the Code Executes

### ISSUE THREAD

**Issue by nabeelomer** [joyent/http-parser#230]
`First-chance exception at 0xCCCCCCCC in Web Server.exe: 0xC0000005: Access violation executing location 0xCCCCCCCC.
Unhandled exception at 0xCCCCCCCC in Web Server.exe: 0xC0000005: Access violation executing location 0xCCCCCCCC.`
Everytime I use the parser to parse HTTP Requests, the violation above occurs!

My Code:
```C++
char recvbuf[DEFAULT_BUFLEN];
recv(ClientSocket, recvbuf, DEFAULT_BUFLEN, 0);
http_parser_settings s;
http_parser_init(&parser, HTTP_REQUEST);
http_parser_execute(&parser, &s, recvbuf,strlen(recvbuf));
```
Why is it happening? Am I doing something wrong?

**Comment by clifffrey** [comment]
You did not initialize the http_parser_settings struct. If you add something like
memset(&s, 0, sizeof(s));
before the http_parser_execute, then it will likely not crash.

**Comment by nabeelomer** [comment]
@clifffrey I used `memset(&s,0,sizeof(s));` but it still is crashing, but the line where the exception occurs has changed.

**Comment by nabeelomer** [comment]
@clifffrey I used the code and the line where the exception occurs has changed but it is still happening.

**Comment by leakim** [comment]
recvbuf is not null terminated (this is probably why you get an error) and you must save how much was read by recv() and pass that to _execute

char recvbuf[DEFAULT_BUFLEN];
int bytes_read = recv(ClientSocket, recvbuf, DEFAULT_BUFLEN, 0);
http_parser_settings s;
http_parser_init(&parser, HTTP_REQUEST);
http_parser_execute(&parser, &s, recvbuf, bytes_read);

**Comment by nabeelomer** [comment]
@leakim is there a way I can add null termination to `recvbuf`

**Comment by nabeelomer** [comment]
@leakim I used:
```C++
char recvbuf[DEFAULT_BUFLEN];
	int recvd = recv(ClientSocket, recvbuf, DEFAULT_BUFLEN, 0);
	memset(recvbuf, '\0', sizeof(char)*DEFAULT_BUFLEN);
	http_parser_init(p, HTTP_REQUEST);
	http_parser_settings s;
	http_parser_execute(p, &s, recvbuf, recvd);
```
But I am still getting a Access Violation Exception. If you have any code that uses the parser can you post an excerpt of it?

**Comment by clifffrey** [comment]
Your example code is still not running memset on the http_parser_settings structure. In your code, you are running memset on recvbuf (which doesn't need it), instead of running it on the http_parser_settings structure.
In addition, by running memset on recvbuf, you are overwriting all of the data that the recv() call returned, which seems unlikely to be what you want.

**Comment by nabeelomer** [comment]
@clifffrey oh, you are right, I didn't notice.

**Comment by indutny** [comment]
Closing the issue?

**Comment by indutny** [comment]
Closing the issue?
