### ISSUE TITLE
Feature request-  Adding in user data for access in callbacks

### ISSUE THREAD

**Issue by ahonkan** [joyent/http-parser#249]
I find I have to use global variables to pass the header-complete, message-complete events etc.  between the callback and the thread that is polling a socket for data.  Can there be a void pointer in the parser struct that I can use to assign to my own structs so that I can use the callbacks to set particular values in my passed structure?

I could make my structure global and have the callbacks access the elements directly but that's not neat in a multi-threaded environment.

Thanks

**Comment by hissohathair** [comment]
Doesn't that already exists in the parser_data struct?

```c
  http_parser parser;
  http_parser_init(&parser, HTTP_BOTH);
  parser.data = (void*)&your_struct;

**Comment by indutny** [comment]
Yeah, this is already present. Sorry!

**Comment by lberezy** [comment]
Perhaps some more documentation is necessary on the usage of this as it definitely wasn't super clear from the read-me.

**Comment by indutny** [comment]
@lberezy this is very usual for C libraries, but if you feel like you want it - I'm absolutely fine with reviewing a Pull Request ;)

**Comment by lberezy** [comment]
Definitely, I'll put something together.

There's a specific use case that highlights this problem (passing thread local data between a thread and an asynchronous modelled object) - in fact it's the problem I was trying to work around and what lead me here. I hope to address this so others don't have the same problem, or worse, think "http-parser" doesn't play nice with threads, time to use a different library...

**Comment by lberezy** [comment]
sent ;)

https://github.com/joyent/http-parser/pull/256
