### ISSUE TITLE
Non standard header fields

### ISSUE THREAD

**Issue by daeon** [joyent/http-parser#262]
What's the official policy on supporting non standard header formats?

Some http site send invalid header fields such at the one below:
http://www.bundesfinanzministerium.de/

Header field (Note line 4, JSESSIONID...): 
HTTP/1.1 200 OK
Date: Fri, 14 Aug 2015 13:13:27 GMT
Server: HTTP/1.1
JSESSIONID=0F543A6E793443D8EC22E7A8FB9419DC; Path=/cae: 
Cache-Control: no-cache
Content-Type: text/html;charset=utf-8
Content-Language: de
Content-Length: 83428
Age: 351
X-Cache: HIT from c8
X-Cache-Lookup: HIT from c8:80
Via: M1, 1.1 c8 (squid)
Connection: keep-alive

The fix is quite simple and I can file in a pull request.

**Comment by indutny** [comment]
We're being strict on this. This is a malformed request.
